---
 
 - name: Delete {{ name }} persistent volume
   shell: "kubectl delete persistentvolume {{ name }}"
   ignore_errors: yes
 
 - name: Wait for {{ name }} persistent volume to be deleted
   shell: "kubectl get persistentvolumes"
   register: result
   until: result.stdout.find(name) == -1
   retries: "{{ retry.max }}"
   delay: "{{ retry.delay }}"

 - name: Create {{ name }} persistent volume
   shell: "kubectl create -f {{ yamls }}/{{ name }}-persistent-volume.yml"
 
 - name: Wait for {{ name }} persistent volume to be created
   shell: "kubectl get persistentvolume --namespace {{ ns }}"
   register: result
   until: result.stdout.find(name) != -1
   retries: "{{ retry.max }}"
   delay: "{{ retry.delay }}"
